apiVersion: v1
kind: Service
metadata:
  name: secure-app-service
  labels:
    app: secure-app
spec:
  # This creates an AWS Load Balancer (ELB)
  type: LoadBalancer 
  selector:
    # This MUST match the label in your Deployment's template
    app: secure-app 
  ports:
    - protocol: TCP
      port: 80         # The port exposed to the internet
      targetPort: 8080   # The port your container is listening on
