name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # Automatically triggers when pushing to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 3. Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 4. Build Docker Image
        run: |
          # Build the image using the commit SHA for full traceability
          docker build -t eks-armor-app:${{ github.sha }} .

      - name: 5. Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'eks-armor-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # Fails the pipeline if CRITICAL or HIGH vulnerabilities are found
          severity: 'CRITICAL,HIGH'

      - name: 6. Push to Amazon ECR
        run: |
          # Use the registry and repo directly from secrets
          REPO_URL="${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}"
          
          echo "Pushing to: $REPO_URL"
          docker tag eks-armor-app:${{ github.sha }} $REPO_URL:${{ github.sha }}
          docker tag eks-armor-app:${{ github.sha }} $REPO_URL:latest
          docker push $REPO_URL:${{ github.sha }}
          docker push $REPO_URL:latest

      - name: 7. Deploy to Amazon EKS Cluster PROD
        run: |
          REGISTRY="${{ secrets.ECR_REGISTRY }}"
          REPO="${{ secrets.ECR_REPOSITORY }}"
          TAG="${{ github.sha }}"
         
          # Clean Construction: REGISTRY/REPO:TAG
          # This prevents the duplicated ".dkr.ecr..." error
          FULL_IMAGE="$REGISTRY/${REPO}:${TAG}"
          
          echo "Deploy image $FULL_IMAGE"
          sed -i "s|IMAGE_PLACEHOLDER|$FULL_IMAGE|g" k8s/deploymets-secure-app.yaml
          
          # Update Kubeconfig context and apply changes to the cluster
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
          kubectl apply -f k8s/deploymets-secure-app.yaml
          kubectl apply -f k8s/services-secure-app.yaml
